import Link from 'next/link';
import AuthButton from './AuthButton';

export const metadata = {
  title: 'IcellStore',
  description: 'Generated by Jose Luis',
}
 
export default function RootLayout({ children }) {
 return (
    <html>
      <body>
        <main>
          <nav>
            {/* <Link href="/">
              Home
            </Link>
            <Link href="/contents">
              Productos
            </Link> */}
            {/* <AuthButton /> */}
          </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
